name: mirinae_gugu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+917
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  carousel_slider: ^4.0.0
  # flutter_linkify: ^5.0.2
  rxdart: ^0.27.2
  #cloud_firestore: ^0.13.6
  font_awesome_flutter: ^9.1.0
  #google_sign_in: ^4.4.6
  shared_preferences: ^2.0.7
  flutter_signin_button: ^2.0.0
  # Add the dependency for the FlutterFire plugin for Google Analytics
  #  firebase_analytics: ^5.0.2
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  #firebase_auth: ^0.16.1
  image_picker: ^0.7.0
  path_provider: ^2.0.1
  sizer: ^2.0.15
  fluttertoast: ^8.0.8
  get: 3.24.0
  flutter_svg: ^0.19.1
  intl: ^0.17.0
  #youtube_player_flutter: ^8.0.0
  youtube_player_flutter: ^8.0.0
  #shared_preferences: ^0.5.12+4
  cached_network_image: ^3.1.0
  camera: ^0.9.2
  google_speech: ^2.0.1
  sound_stream:
  audioplayers: ^0.19.1
  flutter_animation_progress_bar: ^2.0.1
  noise_meter: ^3.0.2
  share: ^2.0.4
  flutter_inappwebview: ^5.3.2
  flutter_audio_recorder:
  permission_handler:
  storage_path:
  flutter_screenutil: ^5.0.2
  flutter_switch: ^0.3.2
  introduction_screen: ^2.1.0


dependency_overrides:
  file: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lejinhy-speech-to-text-11be68205205.json
    - assets/hedgehog.jpeg
    - assets/retry.png
    - assets/duk2.jpg
    - assets/oral_structure 2.png
    - assets/1_screen_start.png
    - assets/2_screen_login.png
    - assets/GGJJ_logo.JPG
    - assets/icons/book.png
    - assets/icons/home.png
    - assets/icons/more.png
    - assets/icons/record_mic.png
    - assets/mouth/1_b.png
    - assets/mouth/2_bb.png
    - assets/mouth/3_p.png
    - assets/mouth/4_m.png
    - assets/mouth/5_d.png
    - assets/mouth/6_dd.png
    - assets/mouth/7_t.png
    - assets/mouth/8_n.png
    - assets/mouth/9_s.png
    - assets/mouth/10_ss.png
    - assets/mouth/11_l.png
    - assets/mouth/12_j.png
    - assets/mouth/13_jj.png
    - assets/mouth/14_ts.png
    - assets/mouth/15_g.png
    - assets/mouth/16_gg.png
    - assets/mouth/17_k.png
    - assets/mouth/18_y.png
    - assets/mouth/19_h.png
    - assets/test_chapter/1_newyear.png
    - assets/test_chapter/2_spring.png
    - assets/test_chapter/3_health.png
    - assets/test_chapter/4_animal.png
    - assets/test_chapter/5_emotion.png
    - assets/test_chapter/6_summer.png
    - assets/test_chapter/7_fruit.png
    - assets/test_chapter/8_fall.png
    - assets/test_chapter/9_work.png
    - assets/test_chapter/10_house.png
    - assets/test_chapter/11_winter.png
    - assets/test_chapter/12_family.png
    - assets/test_chapter/13_foreign.png
    - assets/test_achievement/bad.png
    - assets/test_achievement/good.png
    - assets/test_achievement/success.png
    - assets/Walkthrough/Walkthrough-1.png
    - assets/Walkthrough/Walkthrough-2.png
    - assets/Walkthrough/Walkthrough-3.png
    - assets/Walkthrough/Walkthrough-4.png
    - assets/Walkthrough/Walkthrough-5.png
    - assets/Walkthrough/Walkthrough-6.png
    - assets/Walkthrough/Walkthrough-7.png
    - assets/Walkthrough/Walkthrough-8.png
    - assets/Walkthrough/Walkthrough-9.png
    - assets/Walkthrough/Walkthrough-10.png
    - assets/Walkthrough1/Walkthrough-1.jpg
    - assets/Walkthrough1/Walkthrough-2.jpg
    - assets/Walkthrough1/Walkthrough-3.jpg
    - assets/Walkthrough1/Walkthrough-4.jpg
    - assets/Walkthrough1/Walkthrough-5.jpg
    - assets/Walkthrough1/Walkthrough-6.jpg
    - assets/Walkthrough1/Walkthrough-7-1.jpg
    - assets/Walkthrough1/Walkthrough-7-2.jpg
    - assets/Walkthrough1/Walkthrough-8.jpg

  fonts:
    - family: cookie
      fonts:
        - asset: assets/fonts/CookieRun Regular.ttf

    - family: origin
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf


    - family: chosun100
      fonts:
        - asset: assets/fonts/ChosunCentennial_ttf.ttf

    - family: nexon
      fonts:
        - asset: assets/fonts/NEXON Lv1 Gothic Low OTF.otf
        - asset: assets/fonts/NEXON Lv1 Gothic Low OTF Bold.otf
        - asset: assets/fonts/NEXON Lv1 Gothic Low OTF Light.otf


    - family: nunum
      fonts:
        - asset: assets/fonts/NanumGothic.ttf

    - family: mbc
      fonts:
        - asset: assets/fonts/MBC 1961 M.ttf

    #- images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages